/** @type {import('prettier').Config} */
// eslint-disable-next-line no-undef
module.exports = {
    arrowParens: "always",
    bracketSpacing: true,
    embeddedLanguageFormatting: "auto",
    htmlWhitespaceSensitivity: "css",
    insertPragma: false,
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    printWidth: 120,
    proseWrap: "preserve",
    quoteProps: "as-needed",
    requirePragma: false,
    semi: true,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "es5",
    useTabs: false,
    vueIndentScriptAndStyle: true,
    pluginSearchDirs: true,
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    sortImports: true,
    endOfLine: "lf",
    importOrder: [
        "^(react/(.*)$)|^(react$)",
        "",
        "^(next/(.*)$)|^(next$)",
        "",
        "<THIRD_PARTY_MODULES>",
        "",
        "^@/(.*)$",
        "",
        "^[./]",
        "",
        "^react-icons/(.*)$",
        "",
    ],
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    plugins: [
        "prettier-plugin-tailwindcss",
        "prettier-plugin-organize-imports",
        "prettier-plugin-import-sort",
        "prettier-plugin-css-order",
        "@trivago/prettier-plugin-sort-imports",
        "@ianvs/prettier-plugin-sort-imports",
        "@prettier/plugin-pug",
        "@shopify/prettier-plugin-liquid",
        "prettier-plugin-astro",
        "prettier-plugin-organize-attributes",
        "prettier-plugin-style-order",
    ],
};
